#include "eboot_patch_structures.h"

extern texture_region_info_array g_union_2521_1_regions;
extern single_instruction_patch_array g_union_2521_1_instruction_patches;
extern byte_sequence_patch_array g_union_2529_0_byte_sequence_patches;
extern single_instruction_patch_array g_union_2529_0_instruction_patches;
extern texture_region_info_array g_union_2530_1_regions;
extern single_instruction_patch_array g_union_2530_1_instruction_patches;
extern texture_region_info_array g_union_2531_1_regions;
extern single_instruction_patch_array g_union_2533_5_instruction_patches;
extern texture_region_info_array g_union_2533_7_regions;
extern texture_region_info_array g_union_2533_8_regions;
extern texture_region_info_array g_union_2533_9_regions;
extern texture_region_info_array g_union_2533_10_regions;
extern texture_region_info_array g_pr_0_regions;
extern single_instruction_patch_array g_pr_0_single_instruction_patches;
extern byte_sequence_patch_array g_pr_byte_sequence_patches;
extern texture_region_info_array g_pr_4_regions;
extern single_instruction_patch_array g_pr_4_single_instruction_patches;
extern single_instruction_patch_array g_variable_width_font_patch;
extern rgt_rgo_pr_image_info_array g_rgo_pr_image_infos;
extern rgt_rgo_script_element_array g_script_0_elements;